### ISSUE TITLE
Refactor(fe): 타입 지정, Modal 구현, 코드 개선

### ISSUE THREAD

**Issue by dev-junehee** [FE5-TEAM9/sweethome#171]
### Todo
- [ ] 타입스크립트 수정 - any 삭제
- [ ] Modal 컴포넌트 구현 (재사용 고려)
- [ ] alert 등 경고창 대신 Modal 사용
- [ ] 불필요한 코드 삭제 및 코드 개선
